<?php

namespace Dimando\TodoListBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{

    public function getTasks($limit = 3)
    {
        $req = $this->createQueryBuilder('t')
            ->addSelect('t')
            ->orderBy('t.id', 'DESC');

        $req->setMaxResults($limit);

        return $req->getQuery()
            ->getResult();
    }
}
